[project]
name = "pythonaufgaben"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.9.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
